module.exports = Object.freeze({
    TBL_USER:'tbl_users',
    TBL_DONATION:'tbl_donation_details',
    TBL_DONATION_ITEM:'tbl_donation_items',
    TBL_OTP:'tbl_otp',
    TBL_ROLE:'tbl_roles',
    TBL_USERS_ROLES:'tbl_users_roles',
    TBL_PASSWORD_RESET:'tbl_password_resets',
    TBL_ITEM:'tbl_items',
    TBL_NEW_DONATION:'tbl_donations',
    TBL_ELEC_DONATION:'tbl_elec_donation',
    TBL_ELEC_DONATION_ITEM:'tbl_elec_donation_item',
    TBL_MANUAL_DONATION:'tbl_manual_donation',
    TBL_MANUAL_DONATION_ITEM:'tbl_manual_donation_item',
    TBL_VOUCHERS:'tbl_vouchers',
    TBL_DONATION_TYPES:'tbl_donation_types',
    TBL_EMPLOYEES:'tbl_employees',
    TBL_ADMIN : 'tbl_admin',
    TBL_EMP_ROLES: 'tbl_emp_roles',
    TBL_RECEIPT:'tbl_receipt',
    TBL_CHECKIN:'tbl_checkin',
    TBL_ROOMS:'tbl_rooms',
    TBL_HOLDIN:'tbl_holdin',
    TBL_ROOM_CATEGORY:'tbl_rooms_category',
    TBL_FACILITY:'tbl_facility',
    Tbl_CANCELLEDVOUCHERS:'tbl_cancelled_vouchers',
    Tbl_DHARAMSALA: 'tbl_dharmasala'
}); 